/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile_expressions;

import org.eclipse.xtext.scoping.IScopeProvider;

import edu.kit.iti.formal.pse.worthwhile.WorthwhileRuntimeModule;
import edu.kit.iti.formal.pse.worthwhile_expressions.scoping.WorthwhileExpressionsScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WorthwhileExpressionsRuntimeModule extends WorthwhileRuntimeModule {

	@Override
	public final Class<? extends IScopeProvider> bindIScopeProvider() {
		return WorthwhileExpressionsScopeProvider.class;
	}

}
