/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class WorthwhileRuntimeModule extends
	edu.kit.iti.formal.pse.worthwhile.AbstractWorthwhileRuntimeModule {

}
