/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.z3model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Z3ModelRuntimeModule extends edu.kit.iti.formal.pse.worthwhile.z3model.AbstractZ3ModelRuntimeModule {

}
