<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="worthwhile"
    nsURI="http:///edu.kit.iti.formal.pse.worthwhile" nsPrefix="worthwhile">
  <eSubpackages name="ast" nsURI="http:///ast.model.worthwhile.pse.formal.iti.kit.edu"
      nsPrefix="edu.kit.iti.formal.pse.worthwhile.model.ast">
    <eClassifiers xsi:type="ecore:EClass" name="Program" eSuperTypes="#//ast/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="functionDeclarations"
          ordered="false" upperBound="-1" eType="#//ast/FunctionDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mainBlock" ordered="false"
          eType="#//ast/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="axioms" ordered="false"
          upperBound="-1" eType="#//ast/Axiom" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ASTNode" abstract="true">
      <eOperations name="accept">
        <eParameters name="visitor" lowerBound="1" eType="#//ast/ASTNodeVisitor"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionInLine" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ASTNodeVisitor" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true"
        eSuperTypes="#//ast/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//ast/ASTNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true" eSuperTypes="#//ast/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayLength" eSuperTypes="#//ast/UnaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayLiteral" eSuperTypes="#//ast/Literal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" ordered="false"
          upperBound="-1" eType="#//ast/Expression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//ast/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//ast/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" ordered="false"
          lowerBound="1" eType="#//ast/PrimitiveType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="size" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//ast/ASTNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//ast/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//ast/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation" abstract="true" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
          lowerBound="1" eType="#//ast/VariableReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false"
          lowerBound="1" eType="#//ast/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" ordered="false"
          eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//ast/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Axiom" eSuperTypes="#//ast/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" ordered="false"
          upperBound="-1" eType="#//ast/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//ast/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//ast/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="trueBlock" ordered="false"
          lowerBound="1" eType="#//ast/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="falseBlock" ordered="false"
          eType="#//ast/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Disjunction" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Equal" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Equivalence" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExistsQuantifier" eSuperTypes="#//ast/QuantifiedExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="QuantifiedExpression" abstract="true"
        eSuperTypes="#//ast/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
          lowerBound="1" eType="#//ast/VariableDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
          eType="#//ast/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForAllQuantifier" eSuperTypes="#//ast/QuantifiedExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//ast/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actuals" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="function" ordered="false"
          lowerBound="1" eType="#//ast/FunctionDeclaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//ast/ASTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" ordered="false"
          upperBound="-1" eType="#//ast/Precondition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postconditions" ordered="false"
          upperBound="-1" eType="#//ast/Postcondition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false"
          upperBound="-1" eType="#//ast/VariableDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          lowerBound="1" eType="#//ast/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" ordered="false"
          lowerBound="1" eType="#//ast/Type" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Precondition" eSuperTypes="#//ast/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Postcondition" eSuperTypes="#//ast/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Greater" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="GreaterOrEqual" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Implication" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//ast/Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//ast/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Invariant" eSuperTypes="#//ast/Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Less" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="LessOrEqual" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
          lowerBound="1" eType="#//ast/Block" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" ordered="false"
          upperBound="-1" eType="#//ast/Invariant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//ast/Sign"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sign" abstract="true" eSuperTypes="#//ast/UnaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Modulus" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Negation" eSuperTypes="#//ast/UnaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//ast/Sign"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//ast/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" ordered="false"
          lowerBound="1" eType="#//ast/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Subtraction" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Unequal" eSuperTypes="#//ast/BinaryExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariableReference" eSuperTypes="#//ast/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
          lowerBound="1" eType="#//ast/VariableDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//ast/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="#//ast/ASTNode"/>
  </eSubpackages>
</ecore:EPackage>
