/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class WorthwhileLabelProvider extends DefaultEObjectLabelProvider {

	/**
	 * Creates a new instance of the {@link WorthwhileLabelProvider} class.
	 * 
	 * @param delegate
	 *                This is not even documented in the Xtext documentation, so who knows what this does?
	 */
	@Inject
	public WorthwhileLabelProvider(final AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	/*
	 * //Labels and icons can be computed like this:
	 * 
	 * String text(MyModel ele) { return "my "+ele.getName(); }
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */
}
