/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;
import org.xtext.example.mydsl.typesystem.MyDslTypesystem;
import org.xtext.example.mydsl.validation.MyDslSyntaxErrorMessageProvider;

import de.itemis.xtext.typesystem.ITypesystem;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.xtext.example.mydsl.AbstractMyDslRuntimeModule {

	public Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider() {
		 return MyDslSyntaxErrorMessageProvider.class;
	}
	
	public Class<? extends ITypesystem> bindITypestem() {
	      return MyDslTypesystem.class;
	}
	
}
