/*
* generated by Xtext
*/
package edu.kit.iti.formal.pse.worthwhile.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class WorthwhileOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
