/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WorthwhileUiModule extends edu.kit.iti.formal.pse.worthwhile.ui.AbstractWorthwhileUiModule {
	public WorthwhileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
