/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.expressions.scoping;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.SimpleScope;

import com.google.inject.Inject;

import edu.kit.iti.formal.pse.worthwhile.model.ast.FunctionCall;
import edu.kit.iti.formal.pse.worthwhile.model.ast.FunctionDeclaration;
import edu.kit.iti.formal.pse.worthwhile.model.ast.VariableDeclaration;
import edu.kit.iti.formal.pse.worthwhile.model.ast.VariableReference;

/**
 * A scoping provider that uses the current program state to provide variable declarations.
 * 
 * @author Joachim
 * 
 * @nocheckstyle:methodname (convention requires the method names to contain underscores)
 * 
 */
public class WorthwhileExpressionsScopeProvider extends AbstractDeclarativeScopeProvider {

	/**
	 * The provider for the debug context.
	 */
	private final IWorthwhileContextProvider contextProvider;

	/**
	 * Creates a new instance of the {@link WorthwhileExpressionsScopeProvider} class.
	 * 
	 * @param contextProvider
	 *                The provider for the debug context.
	 */
	@Inject
	public WorthwhileExpressionsScopeProvider(final IWorthwhileContextProvider contextProvider) {
		this.contextProvider = contextProvider;
	}

	/**
	 * Provides the scope for a function call's function reference.
	 * 
	 * @param context
	 *                The function call to provide the scope for.
	 * @param reference
	 *                The corresponding EReference in the Ecore model.
	 * @return A scope in which to look for the referenced function.
	 */
	public final IScope scope_FunctionCall_function(final FunctionCall context, final EReference reference) {
		List<IEObjectDescription> descriptions = new ArrayList<IEObjectDescription>();

		for (FunctionDeclaration funcdec : this.contextProvider.getFunctionDeclarations()) {
			descriptions.add(EObjectDescription.create(funcdec.getName(), funcdec));
		}

		return new SimpleScope(IScope.NULLSCOPE, descriptions);
	}

	/**
	 * Provides the scope for a variable reference.
	 * 
	 * @param context
	 *                The variable reference to provide the scope for.
	 * @param reference
	 *                The corresponding EReference in the Ecore model.
	 * @return A scope in which to look for the referenced variable.
	 */
	public final IScope scope_VariableReference_variable(final VariableReference context, final EReference reference) {
		List<IEObjectDescription> descriptions = new ArrayList<IEObjectDescription>();

		for (VariableDeclaration vardec : this.contextProvider.getVariableDeclarations()) {
			descriptions.add(EObjectDescription.create(vardec.getName(), vardec));
		}

		return new SimpleScope(IScope.NULLSCOPE, descriptions);
	}

}
