/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import edu.kit.iti.formal.pse.worthwhile.expressions.scoping.IWorthwhileContextProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WorthwhileExpressionsUiModule extends edu.kit.iti.formal.pse.worthwhile.expressions.ui.AbstractWorthwhileExpressionsUiModule {
	public WorthwhileExpressionsUiModule(AbstractUIPlugin plugin, IWorthwhileContextProvider contextProvider) {
		super(plugin);
		this.contextProvider = contextProvider;
	}
	
	public WorthwhileExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	private IWorthwhileContextProvider contextProvider;
	
	public IWorthwhileContextProvider bindIWorthwhileContextProvider() {
		return this.contextProvider;
	}
}
