/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.xtext.example.mydsl.typesystem.ExprTypesystem;
import org.xtext.example.mydsl.ui.autoedit.MyDslAutoEditStrategyProvider;

import de.itemis.xtext.typesystem.ITypesystem;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends org.xtext.example.mydsl.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ITypesystem> bindITypesystem() {
	    return ExprTypesystem.class;
	  }
	
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return MyDslAutoEditStrategyProvider.class;
	}
}
