/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import de.itemis.xtext.typesystem.ITypesystem;
import org.xtext.example.mydsl.typesystem.*;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends org.xtext.example.mydsl.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ITypesystem> bindITypesystem() {
	    return ExprTypesystem.class;
	  }
}
