/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant.
 */
public class WorthwhileProposalProvider extends AbstractWorthwhileProposalProvider {

}
