/*
* generated by Xtext
*/
package edu.kit.iti.formal.pse.worthwhile.ui.contentassist;

import edu.kit.iti.formal.pse.worthwhile.ui.contentassist.AbstractWorthwhileProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WorthwhileProposalProvider extends AbstractWorthwhileProposalProvider {

}
