/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.expressions.ui.activator;

import static com.google.inject.Guice.createInjector;
import static com.google.inject.util.Modules.override;

import java.util.HashMap;
import java.util.Map;

import org.apache.log4j.Logger;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Injector;
import com.google.inject.Module;

import edu.kit.iti.formal.pse.worthwhile.expressions.scoping.IWorthwhileContextProvider;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WorthwhileExpressionsActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private IWorthwhileContextProvider contextProvider;
	private static WorthwhileExpressionsActivator INSTANCE;

	public Injector getInjector(String languageName) {
		if (injectors.size() == 0) {
			try {
				registerInjectorFor("edu.kit.iti.formal.pse.worthwhile.expressions.WorthwhileExpressions");
				
			} catch (Exception e) {
				Logger.getLogger(getClass()).error(e.getMessage(), e);
			}
		}
		
		return injectors.get(languageName);
	}
	
	public void setContextProvider(IWorthwhileContextProvider contextProvider) {
		this.contextProvider = contextProvider;
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
	}
	
	protected void registerInjectorFor(String language) throws Exception {
		injectors.put(language, createInjector(
		  override(override(getRuntimeModule(language)).with(getSharedStateModule())).with(getUiModule(language))));
	}
	
	@Override
	public void stop(BundleContext context) throws Exception {
		injectors.clear();
		INSTANCE = null;
		super.stop(context);
	}
	
	public static WorthwhileExpressionsActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		if ("edu.kit.iti.formal.pse.worthwhile.expressions.WorthwhileExpressions".equals(grammar)) {
		  return new edu.kit.iti.formal.pse.worthwhile.expressions.WorthwhileExpressionsRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getUiModule(String grammar) {
		if ("edu.kit.iti.formal.pse.worthwhile.expressions.WorthwhileExpressions".equals(grammar)) {
		  return new edu.kit.iti.formal.pse.worthwhile.expressions.ui.WorthwhileExpressionsUiModule(this, this.contextProvider);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
