/*
 * generated by Xtext
 */
package edu.kit.iti.formal.pse.worthwhile.z3model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Z3ModelUiModule extends edu.kit.iti.formal.pse.worthwhile.z3model.ui.AbstractZ3ModelUiModule {
	public Z3ModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
